AnimalShelter/Models/Animal.cs
using System;

namespace AnimalShelter.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public DateTime Admittance { get; set; }
    public string Breed { get; set; }
    public int TypeId { get; set; }
    public virtual Type Type { get; set; }
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public virtual DbSet<Type> Types { get; set; }
    public DbSet<Animal> Animals { get; set; }
    
    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/Models/Type.cs
using System.Collections.Generic;

namespace AnimalShelter.Models
{
  public class Type
  {
    public Type()
    {
      this.Animals = new HashSet<Animal>();
    }

    public int TypeId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Animal> Animals { get; set; }
  }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;

    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.Include(animals => animals.Type).ToList();
      return View(model);
    }

/*     [HttpPost]
    public ActionResult Index(string orderBy)
    {
      List<Animal> model = _db.Animals.Include(animals => animals.Type).ToList().OrderBy(animal => animal.orderBy);
      return View(model);
    } */

    public ActionResult Create()
    {
      ViewBag.TypeId = new SelectList(_db.Types, "TypeId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }
  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

AnimalShelter/Controllers/TypesController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Controllers
{
  public class TypesController : Controller
  {
    private readonly AnimalShelterContext _db;
    public TypesController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Type> model = _db.Types.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Type type)
    {
      _db.Types.Add(type);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Type thisType = _db.Types.FirstOrDefault(type => type.TypeId == id);
      return View(thisType);
    }
  }
}

AnimalShelter/Views/Animals/Create.cshtml
@model AnimalShelter.Models.Animal

<h4>Add a new animal</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Gender)
  @Html.TextBoxFor(model => model.Gender)
  @Html.LabelFor(model => model.Admittance)
  @Html.TextBoxFor(model => model.Admittance, new { @type = "date"})
  @Html.LabelFor(model => model.Breed)
  @Html.TextBoxFor(model => model.Breed)

  @Html.LabelFor(model => model.Type)
  @Html.DropDownList("TypeId")

  <input type="submit" value="Add new animal" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all items", "Index")</p>

AnimalShelter/Views/Animals/Details.cshtml
@model AnimalShelter.Models.Animal

<h2>Animal Details</h2>
<hr/>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Gender): @Html.DisplayFor(model => model.Gender)</h3>
<h3>@Html.DisplayNameFor(model => model.Admittance): @Html.DisplayFor(model => model.Admittance)</h3>
<h3>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)</h3>

<p>@Html.ActionLink("Back to animals list", "Index")</p>

AnimalShelter/Views/Animals/Index.cshtml
@using AnimalShelter.Models;
@model List<AnimalShelter.Models.Animal>;

@if (@Model.Count == 0)
{
  <h3>No animals have been added yet!</h3>
} 

@foreach (Animal animal in Model)
{
  <li>@Html.ActionLink($"{animal.Name}", "Details", new { id = animal.AnimalId }) | @animal.Type.Name</li>
}

@* <form action="Index" method="post">
  <label for="orderBy">Order by:</label>
  <select id="orderBy" name="orderBy">
    <option value="Breed">Breed</option>
    <option value="Admittance">Admittance</option>
  </select>
  <input type="submit" value="Sort By">
</form> *@

<p>@Html.ActionLink("Add new animal", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

AnimalShelter/Views/Home/Index.cshtml
<h1>Welcome to the Animal Shelter!</h1>
<p>@Html.ActionLink("See all types", "Index", "Types")</p>
<p>@Html.ActionLink("See all animals", "Index", "Animals")</p>

AnimalShelter/Views/Types/Create.cshtml
@model AnimalShelter.Models.Type

<h4>Add a new animal type</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new type" />
}

<p>@Html.ActionLink("Show all animal types", "Index")</p>

AnimalShelter/Views/Types/Details.cshtml
@using AnimalShelter.Models;
@model AnimalShelter.Models.Type;

<h2>Animal type details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<ul>
@if (@Model.Animals.Count == 0)
{
  <p>No animals found in this type</p>
}

@foreach (Animal animal in @Model.Animals)
{
  <li>Animal name: @animal.Name</li>
}

<p>@Html.ActionLink("Back to animal types", "Index")</p>

AnimalShelter/Views/Types/Index.cshtml
@using AnimalShelter.Models;
@using Type = AnimalShelter.Models.Type;
@model List<AnimalShelter.Models.Type>;


<h1>Animal Types</h1>
<hr/>

@if (@Model.Count == 0)
{
  <h3>No aminal types have been added yet</h3>
}

@foreach (Type type in Model)
{
  <li>@Html.ActionLink($"{type.Name}", "Details", new { id = type.TypeId })</li>
}

<p>@Html.ActionLink("Add new animal type", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>